### PR TITLE
Add CocoaPods Podspec

### PR DESCRIPTION
**Pull request by adolfo**
Hi Ankit,

Thank you for this awesome library. This pull request adds a CocoaPods Podspec so that it can be used with CocoaPods. Please tag the latest commit and update the `s.version` in `SwiftMQTT.podspec` accordingly if you don't prefer `1.0.0`.

Thank you

### CODE REVIEW

**Comment by f2m2rd** [comment]
@aciidb0mb3r  👍 for `CocoaPods` support.

**Comment by aciidb0mb3r** [comment]
Thanks, sorry for delay. I'll merge this and create a tag.

**Comment by adolfo** [comment]
Great – thank you!

**Comment by f2m2rd** [comment]
Thanks @adolfo! 
@aciidb0mb3r  Can you please deploy the framework to CocoaPods Trunk? 

https://guides.cocoapods.org/making/getting-setup-with-trunk.html

**Pull request merged**
