### PR TITLE
Swift 4.1 Support

### PR DESCRIPTION
**Pull request by adolfo**
This PR consolidates changes from:
#23 Many lifecycle fixes and optimizations
#30 Add Swift 4 Support

Also addresses:
#31 Sample app does not compile 
#28 Add Swift Package Manager support
#21 Connect or subscribe don't get callbacks when in thread other than main

### CODE REVIEW

**Comment by adolfo** [comment]
Addresses #28

**Comment by adolfo** [comment]
@bhargavg Can you take a look at this when you a few free moments?

**Comment by bhargavg** [comment]
@adolfo  Thanks for doing this !!!

I had a quick glance and found few things missing from #30, #23 (`MQTTDatedSnapshot`, `MQTTReconnectingSession`, etc.,) is this intentional?

**Comment by adolfo** [comment]
@bhargavg Yes, these were removed intentionally. They weren't documented and because I wasn't familiar with them, I was unable to test them. Because of this I felt uncomfortable including them so for now they still exist in the commit history so they can restored if needed. I also don't see a way to `@` the original author of those features.

**Comment by bhargavg** [comment]
Ok, I'll review and get this merged first, then we can see what to do with those un-merged PRs.

**Comment by adolfo** [comment]
@bhargavg Thoughts on this?

**Comment by adolfo** [comment]
@bhargavg If there are no objections I'd like to merge this and publish a new version to CocoaPods. Thoughts?

**Comment by adolfo** [comment]
@bhargavg @Michael-AirMap I'm going to merge this and cut a new release.

**Pull request merged**
